# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(default='draw', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hadron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_quarks', models.IntegerField(default=1)),
                ('location', models.CharField(default='beam', max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadrons', to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Quark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='red', max_length=5)),
                ('flavor', models.CharField(default='up', max_length=7)),
                ('anti', models.BooleanField(default=False)),
                ('is_annihilator', models.BooleanField(default=False)),
                ('hadron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarks', to='game.Hadron')),
            ],
        ),
    ]
